/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardStatisticsHorizontal: typeof import('./resources/ts/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/ts/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./resources/ts/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ErrorHeader: typeof import('./resources/ts/components/ErrorHeader.vue')['default']
    MoreBtn: typeof import('./resources/ts/@core/components/MoreBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./resources/ts/@core/components/ThemeSwitcher.vue')['default']
    UpgradeToPro: typeof import('./resources/ts/components/UpgradeToPro.vue')['default']
  }
}
